# Generated by Django 4.1.1 on 2022-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='The rating the reviewer has given.'),
        ),
    ]
